###############################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: Check Dependencies

on:
  push:
    branches: [main]
    paths:
      - yarn.lock
      - DEPENDENCIES
      - .github/workflows/dependencies.yaml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - yarn.lock
      - DEPENDENCIES
      - .github/workflows/dependencies.yaml
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Dependencies file
        run: java -jar ./scripts/download/org.eclipse.dash.licenses-1.1.1.jar yarn.lock -project automotive.tractusx -summary DEPENDENCIES

      - name: Check for restricted dependencies
        run: |
          restricted=$(grep ' restricted,' DEPENDENCIES || true)
          if [[ -n "$restricted" ]]; then
            echo "The following dependencies are restricted: $restricted"
            exit 1
          fi

      - name: Check if dependencies were changed
        id: dependencies-changed
        run: |
          changed=$(git diff DEPENDENCIES)
          if [[ -n "$changed" ]]; then
            echo "dependencies changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "dependencies not changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload DEPENDENCIES file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: DEPENDENCIES
        if: steps.dependencies-changed.outputs.changed == 'true'

      - name: Signal need to update DEPENDENCIES
        run: |
          echo "Dependencies need to be updated (updated DEPENDENCIES file has been uploaded to workflow run)"
          exit 1
        if: steps.dependencies-changed.outputs.changed == 'true'
